### ISSUE TITLE
Denoting binary and tokens for serialisation

### ISSUE THREAD

**Issue by mnot** [httpwg/structured-header-tests#21]
We need to be able to distinguish binary and token values from strings to be able to serialise them properly. 

There are a couple of strategies that come to mind:

1. In place of strings in `expected`, have objects with a property that explains the target type
2. Use a specific set of values for binaries and tokens that a test suite can identify and serialise appropriately
3. use prefixes and/or suffixes on values to make them recognisable.

(1) has the downside that it complicates the test suite pretty awfully, but (2) and (3) have the downside that the suite won't be able to be very complete (especially for tokens).

(1) has the side benefit that we can have a semi-canonical mapping of SH to JSON.

@phluid61 any thoughts?

**Comment by phluid61** [comment]
My first thought was a prefix, like `"$hello world"` for string, `":foo"` for token, `"*PFQXS==="` for binary (I don't care about colour of paint here).

Having a blessed mapping between SH and JSON would be nice, though.

**Comment by mnot** [comment]
OK, I did a couple of commits and now if something looks like a token, it parses as one; I'm not horribly unhappy with that direction, at least for now.

That leaves binary.

**Comment by mnot** [comment]
Upon reflection, I think we should bite the bullet and say that strings are strings, and binary and tokens are objects formatted like `{"__type": "binary", "value": "..."}`.

**Comment by mnot** [comment]
The other approach we could take would be to have an extra field or fields in the test object, something like `is_binary` -- whose payload of a list of strings. The semantic would be "if you encounter exactly this string in `expected` when serialising, it should be serialised as binary."

But I think I prefer the `__type` approach.

**Comment by mnot** [comment]
See PR.

**Comment by phluid61** [comment]
How about integers and floats?

**Comment by mnot** [comment]
Right now we're relying on the natural delimitation between them (i.e., integers don't have a fractional component). Is that not sufficient?

**Comment by phluid61** [comment]
Depends if your JSON.parse library differentiates `1.0` from `1`. Mine does, so maybe it's not an issue. How does it work in JS/node?

**Comment by mnot** [comment]
Hm. Maybe we can say that _when needed_ you can use `__type` of `float` or `integer` to distinguish them?

**Comment by mnot** [comment]
(and separate from that, are we OK with merging the PR as a start?)

**Comment by phluid61** [comment]
Yep, I'm happy with merging.

**Comment by mnot** [comment]
OK, merged and then a small correction.

My implementation is now passing all tests for parse and serialise (except for a non-critical one on base64 padding, due to a Python limitation). 

I'm going to try to add some more tests for corner cases. Thanks!
