### ISSUE TITLE
binary.json - non-zero pad-bits

### ISSUE THREAD

**Issue by evert** [httpwg/structured-header-tests#3]
I'm trying to figure out why the 'non-zero pad bits' testcase should fail. It looks fine to me, but maybe I'm missing something.

What's incorrect about the encoding?

**Comment by mnot** [comment]
See: https://tools.ietf.org/html/rfc4648#section-3.5

**Comment by mnot** [comment]
(and note that if it's difficult to enforce in implementations, that might be a good argument for relaxing the requirement)

**Comment by evert** [comment]
I see! That will be a bit frustrating to implement. I'm somewhat tempted to just skip that test. Even enforcing padding with `==` felt a bit weird.

**Comment by evert** [comment]
@mnot for what it's worth, I decided to skip the "non-zero pad bits" explicitly. Popular base64 implementations seem to be forgiving enough, and although I'm not really a believer of Postel's law, in this case I feel it's the pragmatic choice to write a custom parser for this.

**Comment by mnot** [comment]
Am considering flipping the requirement for non-zero pad bits, see https://github.com/httpwg/http-extensions/issues/473
