### ISSUE TITLE
draft -17

### ISSUE THREAD

**Issue by mnot** [httpwg/structured-header-tests#39]
Draft 17 *should* be going to IETF Last Call soon, so I want to make sure that the tests are up-to-date. I just did a few commits, other eyes most welcome.

When we're reasonably certain we're up-to-date, we should put a notice in README.

**Comment by mnot** [comment]
Ping @phluid61 @clelland

**Comment by mnot** [comment]
Also, should we change the repo name, e.g., to `structured-field-tests`?

**Comment by phluid61** [comment]
Sure, although "field tests" is a thing.

I've not much to add to the suite, although I'll go through one last time and make sure all the examples in the spec draft are represented.

**Comment by mnot** [comment]
Hm. That makes my implementation fail in two cases, because they get serialised on a single line instead of two. @phluid61 what do you get -- how does your implementation know to separate them?

**Comment by phluid61** [comment]
Ohh, mine casts in the other direction, so the raw array gets cast to a native object before it compares.

Yeah, both 'on two lines' tests need canonical forms.
