### ISSUE TITLE
Serialisation tests

### ISSUE THREAD

**Issue by mnot** [httpwg/structured-header-tests#8]
We need to be able to test the serialisation algorithms too. Probably by annotating when a test is reversible, and/or adding a new member for the canonical form.

**Comment by phluid61** [comment]
Without looking into it, how about assuming anything that isn't `must_fail` can round-trip, and add `"roundtrip_to": "canonical-serialisation"` where necessary?

e.g.:
```diff
diff --git a/binary.json b/binary.json
index 4f86afe..9495ca8 100644
--- a/binary.json
+++ b/binary.json
@@ -16,7 +16,8 @@
       "raw": ["*aGVsbG8*"],
       "header_type": "item",
       "expected": "NBSWY3DP",
-      "can_fail": true
+      "can_fail": true,
+      "roundtrip_to": "*aGVsbG8=*"
     },
     {
       "name": "bad end delimiter",
```
